### ISSUE TITLE
Would this also work for rk3566?

### ISSUE THREAD

**Issue by StuartIanNaylor** [amazingfate/rockchip-multimedia-config#2]
https://github.com/amazingfate/rockchip-multimedia-config/blob/4ecd3f090d610fbdf3aa72708535b33d628c79b6/create-chromium-vda-vea-devices.sh#L11C1-L20C29

```
	*rk3566*)
		{
			echo "type=dec"
			echo "codecs=VP8:VP9:H.264:H.265"
			echo "max-width=3840"
			echo "max-height=2160"
		} > /dev/video-dec0
		;;
	*)
```

**Comment by amazingfate** [comment]
I guess not. You can try changing `*rk3568*)` to `*rk3568*|*rk3566*)`
