### ISSUE TITLE
im confused about the opi5 gpu driver

### ISSUE THREAD

**Issue by develperbayman** [amazingfate/rockchip-multimedia-config#4]
im trying to enable hardware acceleration on debian bookworm .....is this what i need to install the gpu driver? i tried this but it does not work
i know josh riek has an ubuntu distro but i really need a debian server with gfx acceleration

**Comment by amazingfate** [comment]
Pakcgae `rockchip-multimedia-config` is used to do vpu related operation for rockchip's vendor kernel.
It has no relation with gpu driver.
I have packaged gpu driver for bookworm on obs:

Panfork for `5.10 kernel`/`6.1 kernel with arm mali kernel driver`: 
https://software.opensuse.org//download.html?project=home%3Aamazingfate%3Apanfork-mesa&package=libgl1-mesa-dri

Backported mesa for `6.1 kernel with panthor kernel driver`/`mainline kernel`:
https://software.opensuse.org//download.html?project=home%3Aamazingfate%3Amesa-bookworm-backport&package=libgl1-mesa-dri
